[package]
name = "capwriter"
version = "0.1.0"
authors = ["baku4 <bahkhun@gmail.com>"]
description = "Cap aware vector serializer & deserializer"
edition = "2021"
readme = "README.md"
license = "MIT"

[dependencies]
byteorder = "1.4.3"
anyhow = "1.0.53"

[dev-dependencies]
criterion = "0.3.5"
serde = "1.0.136"
bincode = "1.3.3"

[[bench]]
name = "benchmark"
harness = false